version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-api
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: cucumber-test
    depends_on:
      app:
        condition: service_healthy
